// Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.0 (Build Build 211 04/27/2016)
// Created on Fri Feb 10 15:11:08 2017

soc_lab2 soc_lab2_inst
(
	.x1(x1_sig) ,	// input  x1_sig
	.x2(x2_sig) ,	// input  x2_sig
	.x3(x3_sig) ,	// input  x3_sig
	.x4(x4_sig) ,	// input  x4_sig
	.f(f_sig) 	// output  f_sig
);

